name: Sincronização Automática 6 horas

on:


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v2

      - name: Configuração do Git
        run: |
          git config --local user.email "tpchagas@terra.com.br"
          git config --local user.name "GitHub Actions"

      - name: Sincronizar com o Repositório Original
        run: |
          git fetch origin
          git checkout main
          git pull origin main --no-edit
          git push origin main
